/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/viki/ROSta-Bot/src/command2ros/msg/ManualCommand.msg
 *
 */


#ifndef COMMAND2ROS_MESSAGE_MANUALCOMMAND_H
#define COMMAND2ROS_MESSAGE_MANUALCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace command2ros
{
template <class ContainerAllocator>
struct ManualCommand_
{
  typedef ManualCommand_<ContainerAllocator> Type;

  ManualCommand_()
    : fl_articulation_angle(0.0)
    , fr_articulation_angle(0.0)
    , ml_articulation_angle(0.0)
    , mr_articulation_angle(0.0)
    , rl_articulation_angle(0.0)
    , rr_articulation_angle(0.0)
    , fl_drive_speed(0.0)
    , fr_drive_speed(0.0)
    , ml_drive_speed(0.0)
    , mr_drive_speed(0.0)
    , rl_drive_speed(0.0)
    , rr_drive_speed(0.0)
    , drive_duration(0.0)
    , e_stop(false)  {
    }
  ManualCommand_(const ContainerAllocator& _alloc)
    : fl_articulation_angle(0.0)
    , fr_articulation_angle(0.0)
    , ml_articulation_angle(0.0)
    , mr_articulation_angle(0.0)
    , rl_articulation_angle(0.0)
    , rr_articulation_angle(0.0)
    , fl_drive_speed(0.0)
    , fr_drive_speed(0.0)
    , ml_drive_speed(0.0)
    , mr_drive_speed(0.0)
    , rl_drive_speed(0.0)
    , rr_drive_speed(0.0)
    , drive_duration(0.0)
    , e_stop(false)  {
    }



   typedef float _fl_articulation_angle_type;
  _fl_articulation_angle_type fl_articulation_angle;

   typedef float _fr_articulation_angle_type;
  _fr_articulation_angle_type fr_articulation_angle;

   typedef float _ml_articulation_angle_type;
  _ml_articulation_angle_type ml_articulation_angle;

   typedef float _mr_articulation_angle_type;
  _mr_articulation_angle_type mr_articulation_angle;

   typedef float _rl_articulation_angle_type;
  _rl_articulation_angle_type rl_articulation_angle;

   typedef float _rr_articulation_angle_type;
  _rr_articulation_angle_type rr_articulation_angle;

   typedef float _fl_drive_speed_type;
  _fl_drive_speed_type fl_drive_speed;

   typedef float _fr_drive_speed_type;
  _fr_drive_speed_type fr_drive_speed;

   typedef float _ml_drive_speed_type;
  _ml_drive_speed_type ml_drive_speed;

   typedef float _mr_drive_speed_type;
  _mr_drive_speed_type mr_drive_speed;

   typedef float _rl_drive_speed_type;
  _rl_drive_speed_type rl_drive_speed;

   typedef float _rr_drive_speed_type;
  _rr_drive_speed_type rr_drive_speed;

   typedef float _drive_duration_type;
  _drive_duration_type drive_duration;

   typedef uint8_t _e_stop_type;
  _e_stop_type e_stop;




  typedef boost::shared_ptr< ::command2ros::ManualCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::command2ros::ManualCommand_<ContainerAllocator> const> ConstPtr;

}; // struct ManualCommand_

typedef ::command2ros::ManualCommand_<std::allocator<void> > ManualCommand;

typedef boost::shared_ptr< ::command2ros::ManualCommand > ManualCommandPtr;
typedef boost::shared_ptr< ::command2ros::ManualCommand const> ManualCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::command2ros::ManualCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::command2ros::ManualCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace command2ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'command2ros': ['/home/viki/ROSta-Bot/src/command2ros/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::command2ros::ManualCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::command2ros::ManualCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::command2ros::ManualCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::command2ros::ManualCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::command2ros::ManualCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::command2ros::ManualCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::command2ros::ManualCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2cf4afb23be8b461f07a7505be787623";
  }

  static const char* value(const ::command2ros::ManualCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2cf4afb23be8b461ULL;
  static const uint64_t static_value2 = 0xf07a7505be787623ULL;
};

template<class ContainerAllocator>
struct DataType< ::command2ros::ManualCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "command2ros/ManualCommand";
  }

  static const char* value(const ::command2ros::ManualCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::command2ros::ManualCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 fl_articulation_angle\n\
float32 fr_articulation_angle\n\
float32 ml_articulation_angle\n\
float32 mr_articulation_angle\n\
float32 rl_articulation_angle\n\
float32 rr_articulation_angle\n\
\n\
float32 fl_drive_speed\n\
float32 fr_drive_speed\n\
float32 ml_drive_speed\n\
float32 mr_drive_speed\n\
float32 rl_drive_speed\n\
float32 rr_drive_speed\n\
\n\
float32 drive_duration\n\
\n\
bool e_stop\n\
";
  }

  static const char* value(const ::command2ros::ManualCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::command2ros::ManualCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fl_articulation_angle);
      stream.next(m.fr_articulation_angle);
      stream.next(m.ml_articulation_angle);
      stream.next(m.mr_articulation_angle);
      stream.next(m.rl_articulation_angle);
      stream.next(m.rr_articulation_angle);
      stream.next(m.fl_drive_speed);
      stream.next(m.fr_drive_speed);
      stream.next(m.ml_drive_speed);
      stream.next(m.mr_drive_speed);
      stream.next(m.rl_drive_speed);
      stream.next(m.rr_drive_speed);
      stream.next(m.drive_duration);
      stream.next(m.e_stop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ManualCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::command2ros::ManualCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::command2ros::ManualCommand_<ContainerAllocator>& v)
  {
    s << indent << "fl_articulation_angle: ";
    Printer<float>::stream(s, indent + "  ", v.fl_articulation_angle);
    s << indent << "fr_articulation_angle: ";
    Printer<float>::stream(s, indent + "  ", v.fr_articulation_angle);
    s << indent << "ml_articulation_angle: ";
    Printer<float>::stream(s, indent + "  ", v.ml_articulation_angle);
    s << indent << "mr_articulation_angle: ";
    Printer<float>::stream(s, indent + "  ", v.mr_articulation_angle);
    s << indent << "rl_articulation_angle: ";
    Printer<float>::stream(s, indent + "  ", v.rl_articulation_angle);
    s << indent << "rr_articulation_angle: ";
    Printer<float>::stream(s, indent + "  ", v.rr_articulation_angle);
    s << indent << "fl_drive_speed: ";
    Printer<float>::stream(s, indent + "  ", v.fl_drive_speed);
    s << indent << "fr_drive_speed: ";
    Printer<float>::stream(s, indent + "  ", v.fr_drive_speed);
    s << indent << "ml_drive_speed: ";
    Printer<float>::stream(s, indent + "  ", v.ml_drive_speed);
    s << indent << "mr_drive_speed: ";
    Printer<float>::stream(s, indent + "  ", v.mr_drive_speed);
    s << indent << "rl_drive_speed: ";
    Printer<float>::stream(s, indent + "  ", v.rl_drive_speed);
    s << indent << "rr_drive_speed: ";
    Printer<float>::stream(s, indent + "  ", v.rr_drive_speed);
    s << indent << "drive_duration: ";
    Printer<float>::stream(s, indent + "  ", v.drive_duration);
    s << indent << "e_stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.e_stop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMAND2ROS_MESSAGE_MANUALCOMMAND_H
